import { GlobeIcon } from "lucide-react"
import {
  TypescriptPlain,
  JavascriptPlain,
  PythonPlain,
  GoPlain,
  CPlain,
  CplusplusPlain,
  CsharpPlain,
  Html5Plain,
  Css3Plain,
  FsharpPlain,
  GraphqlPlain,
  JavaPlain,
  KotlinPlain,
  LuaPlain,
  YamlPlain,
  PerlPlain,
  PhpPlain,
  RPlain,
  RedisPlain,
  RubyPlain,
  SwiftPlain,
  ObjectivecPlain,
  DockerPlain,
  LessPlainWordmark,
  XmlPlain,
  VisualbasicPlain,
  AzurePlain,
  AzuresqldatabasePlain,
  BashPlain,
  PowershellPlain,
  PostgresqlPlain,
  JsonPlain,
} from "devicons-react"

import {
  ApexIcon,
  ClojureIcon,
  CoffeeScriptIcon,
  HandlebarsIcon,
  MarkdownIcon,
  MySqlIcon,
  RustIcon,
  SASSIcon
} from "./icons"


const Languages = [
  {
    label: "Text",
    value: "plaintext",
    icon: GlobeIcon,
    keyword: ["text", "plaintext"],
  },
  {
    label: "Typescript",
    value: "typescript",
    icon: TypescriptPlain,
    keyword: ["ts", "typescript"],
  },
  {
    label: "Javascript",
    value: "javascript",
    icon: JavascriptPlain,
    keyword: ["js", "javascript"],
  },
  {
    label: "Python",
    value: "python",
    icon: PythonPlain,
    keyword: ["py", "python"],
  },
  {
    label: "Go",
    value: "go",
    icon: GoPlain,
    keyword: ["go", "golang", "gopher"],
  },
  {
    label: "C",
    value: "c",
    icon: CPlain,
    keyword: ["c"],
  },
  {
    label: "C++",
    value: "cpp",
    icon: CplusplusPlain,
    keyword: ["cpp", "cplusplus", "c++"],
  },
  {
    label: "C#",
    value: "csharp",
    icon: CsharpPlain,
    keyword: ["c#", "csharp"],
  },
  {
    label: "HTML",
    value: "html",
    icon: Html5Plain,
    keyword: ["html", "hyper text markup language", "markup"],
  },
  {
    label: "CSS",
    value: "css",
    icon: Css3Plain,
    keyword: ["css", "cascading style sheets"],
  },
  {
    label: "Coffee Script",
    value: "coffeescript",
    icon: CoffeeScriptIcon,
    keyword: ["coffee", "coffeescript", "script"],
  },
  {
    label: "Clojure",
    value: "clojure",
    icon: ClojureIcon,
    keyword: ["clojure", "clj", "cljs", "cljr", "cljc"],
  },
  {
    label: "F#",
    value: "fsharp",
    icon: FsharpPlain,
    keyword: ["f#", "fsharp", "fs", "fsi", "fsx", "fsscript"],
  },
  {
    label: "GraphQL",
    value: "graphql",
    icon: GraphqlPlain,
    keyword: ["graphql", "gql"],
  },
  {
    label: "Handlebars",
    value: "handlebars",
    icon: HandlebarsIcon,
    keyword: ["handlebars", "template"],
  },
  {
    label: "Java",
    value: "java",
    icon: JavaPlain,
    keyword: ["java"],
  },
  {
    label: "Kotlin",
    value: "kotlin",
    icon: KotlinPlain,
    keyword: ["kotlin", "kt"],
  },
  {
    label: "Less",
    value: "less",
    icon: LessPlainWordmark,
    keyword: ["less"],
  },
  {
    label: "Lua",
    value: "lua",
    icon: LuaPlain,
    keyword: ["lua"],
  },
  {
    label: "MySQL",
    value: "mysql",
    icon: MySqlIcon,
    keyword: ["sql", "mysql", "database"],
  },
  {
    label: "Perl",
    value: "perl",
    icon: PerlPlain,
    keyword: ["perl", "pl"],
  },
  {
    label: "PHP",
    value: "php",
    icon: PhpPlain,
    keyword: ["php"],
  },
  {
    label: "R",
    value: "r",
    icon: RPlain,
    keyword: ["r", "data", "Visualization"],
  },
  {
    label: "Redis",
    value: "redis",
    icon: RedisPlain,
    keyword: ["redis", "database"],
  },
  {
    label: "Ruby",
    value: "ruby",
    icon: RubyPlain,
    keyword: ["ruby", "rb"],
  },
  {
    label: "Rust",
    value: "rust",
    icon: RustIcon,
    keyword: ["rust", "rs", "crate"],
  },
  {
    label: "Swift",
    value: "swift",
    icon: SwiftPlain,
    keyword: ["swift", "taylor"],
  },
  {
    label: "Objective C",
    value: "objective-c",
    icon: ObjectivecPlain,
    keyword: ["objective-c", "objective", "c", "m"],
  },
  {
    label: "Docker",
    value: "dockerfile",
    icon: DockerPlain,
    keyword: ["docker", "dockerfile"],
  },
  {
    label: "Apex",
    value: "apex",
    icon: ApexIcon,
    keyword: ["apex"],
  },
  {
    label: "Azcli",
    value: "azcli",
    icon: AzurePlain,
    keyword: ["azcli", "cli", "azure"],
  },
  {
    label: "Bat",
    value: "bat",
    icon: GlobeIcon,
    keyword: ["bat", "windows"],
  },
  {
    label: "CSP",
    value: "csp",
    icon: GlobeIcon,
    keyword: ["csp"],
  },
  {
    label: "INI",
    value: "ini",
    icon: GlobeIcon,
    keyword: ["ini"],
  },
  {
    label: "JSON",
    value: "json",
    icon: JsonPlain,
    keyword: ["json", "parser", "statham"],
  },
  {
    label: "Markdown",
    value: "markdown",
    icon: MarkdownIcon,
    keyword: ["markdown", "md"],
  },
  {
    label: "Msdax",
    value: "msdax",
    icon: GlobeIcon,
    keyword: ["msdax", "x++", "xplusplus"],
  },
  {
    label: "Pascal",
    value: "pascal",
    icon: GlobeIcon,
    keyword: ["pascal", "pas"],
  },
  {
    label: "PostgreSQL",
    value: "pgsql",
    icon: PostgresqlPlain,
    keyword: ["postgresql", "pq", "pg", "database"],
  },
  {
    label: "Postiats",
    value: "postiats",
    icon: GlobeIcon,
    keyword: ["postiats"],
  },
  {
    label: "Powerquery",
    value: "powerquery",
    icon: GlobeIcon,
    keyword: ["powerquery", "windows"],
  },
  {
    label: "Powershell",
    value: "powershell",
    icon: PowershellPlain,
    keyword: ["powershell", "windows"],
  },
  {
    label: "Pug",
    value: "pug",
    icon: GlobeIcon,
    keyword: ["pug", "template"],
  },
  {
    label: "Razor",
    value: "razor",
    icon: GlobeIcon,
    keyword: ["razor", "asp", "net"],
  },
  {
    label: "Redshift",
    value: "redshift",
    icon: GlobeIcon,
    keyword: ["redshift", "aws", "amazon"],
  },
  {
    label: "SB",
    value: "sb",
    icon: GlobeIcon,
    keyword: ["sb"],
  },
  {
    label: "Scheme",
    value: "scheme",
    icon: GlobeIcon,
    keyword: ["scheme"],
  },
  {
    label: "SCSS",
    value: "scss",
    icon: SASSIcon,
    keyword: ["scss"],
  },
  {
    label: "Shell",
    value: "shell",
    icon: BashPlain,
    keyword: ["shell", "bash"],
  },
  {
    label: "SOL",
    value: "sol",
    icon: GlobeIcon,
    keyword: ["sol"],
  },
  {
    label: "SQL",
    value: "sql",
    icon: AzuresqldatabasePlain,
    keyword: ["sql", "database"],
  },
  {
    label: "ST",
    value: "st",
    icon: GlobeIcon,
    keyword: ["st"],
  },
  {
    label: "TCL",
    value: "tcl",
    icon: GlobeIcon,
    keyword: ["tcl"],
  },
  {
    label: "Visual Basic",
    value: "vb",
    icon: VisualbasicPlain,
    keyword: ["vb", "visualbasic"],
  },
  {
    label: "XML",
    value: "xml",
    icon: XmlPlain,
    keyword: ["xml", "extensible markup language", "markup"],
  },
  {
    label: "YAML",
    value: "yaml",
    icon: YamlPlain,
    keyword: ["yaml", "yet another markup language", "markup"],
  },
]
export default Languages
